# Setup
title:        Mining Knowledge Graphs from Text
description:  A Tutorial
baseurl:      ""

# Cayman specific
show_downloads:	false

# About/contact
author:
  name:       Sameer Singh
  url:        http://sameersingh.org 
theme: jekyll-theme-cayman
