# Setup
title:        Knowledge Construction From Text
tagline:      A tutorial
baseurl:      ""

# About/contact
author:
  name:       Sameer Singh
  url:        http://sameersingh.org 
theme: jekyll-theme-cayman